version: '3.8'
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    env_file:
      - .env
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      REDIS_HOST: ${REDIS_HOST}
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - sidekiq

volumes:
  dbdata:
